# Generated by Django 5.2 on 2025-04-15 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('end_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='ports.port')),
                ('start_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='ports.port')),
            ],
        ),
    ]
